import { Product } from '@/src/types';

const P = '/mock-images/default/placeholder.png';

export const products: Product[] = [
  // Apple > iPhone > iPhone 15 Series
  { id: 'p1', seriesId: 's1', categoryId: 'c1', brandId: 'b1', name: 'iPhone 15', description: 'A16 Bionic chip, Dynamic Island', specifications: { Chip: 'A16 Bionic', Display: '6.1" Super Retina XDR', Camera: '48MP Main' }, iconImage: '/mock-images/categories/iphone.png', galleryImages: ['/mock-images/categories/iphone.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p2', seriesId: 's1', categoryId: 'c1', brandId: 'b1', name: 'iPhone 15 Plus', description: 'A16 Bionic chip, larger display', specifications: { Chip: 'A16 Bionic', Display: '6.7" Super Retina XDR', Camera: '48MP Main' }, iconImage: '/mock-images/categories/iphone.png', galleryImages: ['/mock-images/categories/iphone.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p3', seriesId: 's1', categoryId: 'c1', brandId: 'b1', name: 'iPhone 15 Pro', description: 'A17 Pro chip, titanium design', specifications: { Chip: 'A17 Pro', Display: '6.1" Super Retina XDR', Camera: '48MP Main' }, iconImage: '/mock-images/categories/iphone.png', galleryImages: ['/mock-images/categories/iphone.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p4', seriesId: 's1', categoryId: 'c1', brandId: 'b1', name: 'iPhone 15 Pro Max', description: 'A17 Pro chip, largest display', specifications: { Chip: 'A17 Pro', Display: '6.7" Super Retina XDR', Camera: '48MP Main' }, iconImage: '/mock-images/categories/iphone.png', galleryImages: ['/mock-images/categories/iphone.png'], isActive: true, createdAt: '2024-01-18' },
  // Apple > iPhone > iPhone 14 Series
  { id: 'p5', seriesId: 's2', categoryId: 'c1', brandId: 'b1', name: 'iPhone 14', description: 'A15 Bionic chip', specifications: { Chip: 'A15 Bionic', Display: '6.1" Super Retina XDR', Camera: '12MP Main' }, iconImage: '/mock-images/categories/iphone.png', galleryImages: ['/mock-images/categories/iphone.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p6', seriesId: 's2', categoryId: 'c1', brandId: 'b1', name: 'iPhone 14 Plus', description: 'A15 Bionic chip, larger display', specifications: { Chip: 'A15 Bionic', Display: '6.7" Super Retina XDR', Camera: '12MP Main' }, iconImage: '/mock-images/categories/iphone.png', galleryImages: ['/mock-images/categories/iphone.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p7', seriesId: 's2', categoryId: 'c1', brandId: 'b1', name: 'iPhone 14 Pro', description: 'A16 Bionic chip, Dynamic Island', specifications: { Chip: 'A16 Bionic', Display: '6.1" Super Retina XDR', Camera: '48MP Main' }, iconImage: '/mock-images/categories/iphone.png', galleryImages: ['/mock-images/categories/iphone.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p8', seriesId: 's2', categoryId: 'c1', brandId: 'b1', name: 'iPhone 14 Pro Max', description: 'A16 Bionic chip, largest Pro display', specifications: { Chip: 'A16 Bionic', Display: '6.7" Super Retina XDR', Camera: '48MP Main' }, iconImage: '/mock-images/categories/iphone.png', galleryImages: ['/mock-images/categories/iphone.png'], isActive: true, createdAt: '2024-01-18' },
  // Apple > iPad > iPad Pro
  { id: 'p9', seriesId: 's3', categoryId: 'c2', brandId: 'b1', name: 'iPad Pro 11-inch (M2)', description: 'M2 chip, 11-inch Liquid Retina XDR', specifications: { Chip: 'M2', Display: '11" Liquid Retina XDR', Storage: '128GB–2TB' }, iconImage: '/mock-images/categories/ipad.png', galleryImages: ['/mock-images/categories/ipad.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p10', seriesId: 's3', categoryId: 'c2', brandId: 'b1', name: 'iPad Pro 12.9-inch (M2)', description: 'M2 chip, 12.9-inch Liquid Retina XDR', specifications: { Chip: 'M2', Display: '12.9" Liquid Retina XDR', Storage: '128GB–2TB' }, iconImage: '/mock-images/categories/ipad.png', galleryImages: ['/mock-images/categories/ipad.png'], isActive: true, createdAt: '2024-01-18' },
  // Apple > iPad > iPad Air
  { id: 'p11', seriesId: 's4', categoryId: 'c2', brandId: 'b1', name: 'iPad Air (5th Gen)', description: 'M1 chip, 10.9-inch display', specifications: { Chip: 'M1', Display: '10.9" Liquid Retina', Storage: '64GB–256GB' }, iconImage: '/mock-images/categories/ipad.png', galleryImages: ['/mock-images/categories/ipad.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p12', seriesId: 's4', categoryId: 'c2', brandId: 'b1', name: 'iPad Air (6th Gen)', description: 'M2 chip, updated design', specifications: { Chip: 'M2', Display: '10.9" Liquid Retina', Storage: '128GB–512GB' }, iconImage: '/mock-images/categories/ipad.png', galleryImages: ['/mock-images/categories/ipad.png'], isActive: true, createdAt: '2024-01-18' },
  // Apple > iPad > iPad Mini
  { id: 'p13', seriesId: 's5', categoryId: 'c2', brandId: 'b1', name: 'iPad Mini (6th Gen)', description: 'A15 Bionic, 8.3-inch display', specifications: { Chip: 'A15 Bionic', Display: '8.3" Liquid Retina', Storage: '64GB–256GB' }, iconImage: '/mock-images/categories/ipad.png', galleryImages: ['/mock-images/categories/ipad.png'], isActive: true, createdAt: '2024-01-18' },
  // Apple > MacBook > MacBook Air
  { id: 'p14', seriesId: 's6', categoryId: 'c3', brandId: 'b1', name: 'MacBook Air M1', description: 'Apple M1 chip, fanless design', specifications: { Chip: 'M1', Display: '13.3" Retina', RAM: '8GB–16GB' }, iconImage: '/mock-images/categories/macbook.png', galleryImages: ['/mock-images/categories/macbook.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p15', seriesId: 's6', categoryId: 'c3', brandId: 'b1', name: 'MacBook Air M2', description: 'Apple M2 chip, redesigned', specifications: { Chip: 'M2', Display: '13.6" Liquid Retina', RAM: '8GB–24GB' }, iconImage: '/mock-images/categories/macbook.png', galleryImages: ['/mock-images/categories/macbook.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p16', seriesId: 's6', categoryId: 'c3', brandId: 'b1', name: 'MacBook Air M3', description: 'Apple M3 chip, latest Air', specifications: { Chip: 'M3', Display: '13.6" Liquid Retina', RAM: '8GB–24GB' }, iconImage: '/mock-images/categories/macbook.png', galleryImages: ['/mock-images/categories/macbook.png'], isActive: true, createdAt: '2024-01-18' },
  // Apple > MacBook > MacBook Pro
  { id: 'p17', seriesId: 's7', categoryId: 'c3', brandId: 'b1', name: 'MacBook Pro 14-inch M3', description: 'M3 Pro/Max chip, 14-inch', specifications: { Chip: 'M3 Pro/Max', Display: '14.2" Liquid Retina XDR', RAM: '18GB–128GB' }, iconImage: '/mock-images/categories/macbook.png', galleryImages: ['/mock-images/categories/macbook.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p18', seriesId: 's7', categoryId: 'c3', brandId: 'b1', name: 'MacBook Pro 16-inch M3', description: 'M3 Pro/Max chip, 16-inch', specifications: { Chip: 'M3 Pro/Max', Display: '16.2" Liquid Retina XDR', RAM: '18GB–128GB' }, iconImage: '/mock-images/categories/macbook.png', galleryImages: ['/mock-images/categories/macbook.png'], isActive: true, createdAt: '2024-01-18' },
  // Apple > Apple Watch > Series 9
  { id: 'p19', seriesId: 's8', categoryId: 'c4', brandId: 'b1', name: 'Apple Watch Series 9 41mm', description: 'S9 SiP, 41mm case', specifications: { Chip: 'S9 SiP', Display: '41mm Always-On Retina', Sensor: 'Blood Oxygen, ECG' }, iconImage: '/mock-images/categories/apple-watch.png', galleryImages: ['/mock-images/categories/apple-watch.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p20', seriesId: 's8', categoryId: 'c4', brandId: 'b1', name: 'Apple Watch Series 9 45mm', description: 'S9 SiP, 45mm case', specifications: { Chip: 'S9 SiP', Display: '45mm Always-On Retina', Sensor: 'Blood Oxygen, ECG' }, iconImage: '/mock-images/categories/apple-watch.png', galleryImages: ['/mock-images/categories/apple-watch.png'], isActive: true, createdAt: '2024-01-18' },
  // Apple > Apple Watch > Ultra
  { id: 'p21', seriesId: 's9', categoryId: 'c4', brandId: 'b1', name: 'Apple Watch Ultra 2', description: 'S9 SiP, titanium, 49mm', specifications: { Chip: 'S9 SiP', Display: '49mm Always-On Retina', Sensor: 'Depth gauge, Siren' }, iconImage: '/mock-images/categories/apple-watch.png', galleryImages: ['/mock-images/categories/apple-watch.png'], isActive: true, createdAt: '2024-01-18' },
  // Samsung > Galaxy S > S24 Series
  { id: 'p22', seriesId: 's10', categoryId: 'c5', brandId: 'b2', name: 'Galaxy S24', description: 'Exynos 2400, compact flagship', specifications: { Chip: 'Exynos 2400', Display: '6.2" Dynamic AMOLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/galaxy-s.png', galleryImages: ['/mock-images/categories/galaxy-s.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p23', seriesId: 's10', categoryId: 'c5', brandId: 'b2', name: 'Galaxy S24+', description: 'Exynos 2400, larger display', specifications: { Chip: 'Exynos 2400', Display: '6.7" Dynamic AMOLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/galaxy-s.png', galleryImages: ['/mock-images/categories/galaxy-s.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p24', seriesId: 's10', categoryId: 'c5', brandId: 'b2', name: 'Galaxy S24 Ultra', description: 'Snapdragon 8 Gen 3, S Pen', specifications: { Chip: 'Snapdragon 8 Gen 3', Display: '6.8" Dynamic AMOLED', Camera: '200MP Main' }, iconImage: '/mock-images/categories/galaxy-s.png', galleryImages: ['/mock-images/categories/galaxy-s.png'], isActive: true, createdAt: '2024-01-18' },
  // Samsung > Galaxy S > S23 Series
  { id: 'p25', seriesId: 's11', categoryId: 'c5', brandId: 'b2', name: 'Galaxy S23', description: 'Snapdragon 8 Gen 2', specifications: { Chip: 'Snapdragon 8 Gen 2', Display: '6.1" Dynamic AMOLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/galaxy-s.png', galleryImages: ['/mock-images/categories/galaxy-s.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p26', seriesId: 's11', categoryId: 'c5', brandId: 'b2', name: 'Galaxy S23+', description: 'Snapdragon 8 Gen 2, larger', specifications: { Chip: 'Snapdragon 8 Gen 2', Display: '6.6" Dynamic AMOLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/galaxy-s.png', galleryImages: ['/mock-images/categories/galaxy-s.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p27', seriesId: 's11', categoryId: 'c5', brandId: 'b2', name: 'Galaxy S23 Ultra', description: 'Snapdragon 8 Gen 2, S Pen', specifications: { Chip: 'Snapdragon 8 Gen 2', Display: '6.8" Dynamic AMOLED', Camera: '200MP Main' }, iconImage: '/mock-images/categories/galaxy-s.png', galleryImages: ['/mock-images/categories/galaxy-s.png'], isActive: true, createdAt: '2024-01-18' },
  // Samsung > Galaxy Z > Fold
  { id: 'p28', seriesId: 's12', categoryId: 'c6', brandId: 'b2', name: 'Galaxy Z Fold 5', description: 'Snapdragon 8 Gen 2, foldable', specifications: { Chip: 'Snapdragon 8 Gen 2', Display: '7.6" Dynamic AMOLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/galaxy-z.png', galleryImages: ['/mock-images/categories/galaxy-z.png'], isActive: true, createdAt: '2024-01-18' },
  // Samsung > Galaxy Z > Flip
  { id: 'p29', seriesId: 's13', categoryId: 'c6', brandId: 'b2', name: 'Galaxy Z Flip 5', description: 'Snapdragon 8 Gen 2, flip foldable', specifications: { Chip: 'Snapdragon 8 Gen 2', Display: '6.7" Dynamic AMOLED', Camera: '12MP Main' }, iconImage: '/mock-images/categories/galaxy-z.png', galleryImages: ['/mock-images/categories/galaxy-z.png'], isActive: true, createdAt: '2024-01-18' },
  // Samsung > Galaxy Tab > Tab S9
  { id: 'p30', seriesId: 's14', categoryId: 'c7', brandId: 'b2', name: 'Galaxy Tab S9', description: 'Snapdragon 8 Gen 2, 11-inch', specifications: { Chip: 'Snapdragon 8 Gen 2', Display: '11" Dynamic AMOLED', Storage: '128GB–256GB' }, iconImage: P, galleryImages: [P], isActive: true, createdAt: '2024-01-18' },
  { id: 'p31', seriesId: 's14', categoryId: 'c7', brandId: 'b2', name: 'Galaxy Tab S9+', description: 'Snapdragon 8 Gen 2, 12.4-inch', specifications: { Chip: 'Snapdragon 8 Gen 2', Display: '12.4" Dynamic AMOLED', Storage: '256GB–512GB' }, iconImage: P, galleryImages: [P], isActive: true, createdAt: '2024-01-18' },
  { id: 'p32', seriesId: 's14', categoryId: 'c7', brandId: 'b2', name: 'Galaxy Tab S9 Ultra', description: 'Snapdragon 8 Gen 2, 14.6-inch', specifications: { Chip: 'Snapdragon 8 Gen 2', Display: '14.6" Dynamic AMOLED', Storage: '256GB–1TB' }, iconImage: P, galleryImages: [P], isActive: true, createdAt: '2024-01-18' },
  // Samsung > Galaxy Watch > Watch 6
  { id: 'p33', seriesId: 's15', categoryId: 'c8', brandId: 'b2', name: 'Galaxy Watch 6 40mm', description: 'Exynos W930, 40mm', specifications: { Chip: 'Exynos W930', Display: '1.3" Super AMOLED', Sensor: 'BioActive Sensor' }, iconImage: '/mock-images/categories/galaxy-watch.png', galleryImages: ['/mock-images/categories/galaxy-watch.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p34', seriesId: 's15', categoryId: 'c8', brandId: 'b2', name: 'Galaxy Watch 6 44mm', description: 'Exynos W930, 44mm', specifications: { Chip: 'Exynos W930', Display: '1.5" Super AMOLED', Sensor: 'BioActive Sensor' }, iconImage: '/mock-images/categories/galaxy-watch.png', galleryImages: ['/mock-images/categories/galaxy-watch.png'], isActive: true, createdAt: '2024-01-18' },
  { id: 'p35', seriesId: 's15', categoryId: 'c8', brandId: 'b2', name: 'Galaxy Watch 6 Classic', description: 'Exynos W930, rotating bezel', specifications: { Chip: 'Exynos W930', Display: '1.5" Super AMOLED', Sensor: 'BioActive Sensor' }, iconImage: '/mock-images/categories/galaxy-watch.png', galleryImages: ['/mock-images/categories/galaxy-watch.png'], isActive: true, createdAt: '2024-01-18' },
  // Google > Pixel Phone > Pixel 8
  { id: 'p36', seriesId: 's16', categoryId: 'c9', brandId: 'b3', name: 'Pixel 8', description: 'Tensor G3, AI-powered', specifications: { Chip: 'Tensor G3', Display: '6.2" OLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/pixel-phone.png', galleryImages: ['/mock-images/categories/pixel-phone.png'], isActive: true, createdAt: '2024-02-04' },
  { id: 'p37', seriesId: 's16', categoryId: 'c9', brandId: 'b3', name: 'Pixel 8 Pro', description: 'Tensor G3, Pro camera', specifications: { Chip: 'Tensor G3', Display: '6.7" LTPO OLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/pixel-phone.png', galleryImages: ['/mock-images/categories/pixel-phone.png'], isActive: true, createdAt: '2024-02-04' },
  // Google > Pixel Phone > Pixel 7
  { id: 'p38', seriesId: 's17', categoryId: 'c9', brandId: 'b3', name: 'Pixel 7', description: 'Tensor G2', specifications: { Chip: 'Tensor G2', Display: '6.3" OLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/pixel-phone.png', galleryImages: ['/mock-images/categories/pixel-phone.png'], isActive: true, createdAt: '2024-02-04' },
  { id: 'p39', seriesId: 's17', categoryId: 'c9', brandId: 'b3', name: 'Pixel 7 Pro', description: 'Tensor G2, Pro camera', specifications: { Chip: 'Tensor G2', Display: '6.7" LTPO OLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/pixel-phone.png', galleryImages: ['/mock-images/categories/pixel-phone.png'], isActive: true, createdAt: '2024-02-04' },
  // Google > Pixel Tablet
  { id: 'p40', seriesId: 's18', categoryId: 'c10', brandId: 'b3', name: 'Pixel Tablet (2023)', description: 'Tensor G2, with charging speaker dock', specifications: { Chip: 'Tensor G2', Display: '10.95" LCD', Storage: '128GB–256GB' }, iconImage: P, galleryImages: [P], isActive: true, createdAt: '2024-02-04' },
  // Google > Pixel Watch
  { id: 'p41', seriesId: 's19', categoryId: 'c11', brandId: 'b3', name: 'Pixel Watch 2', description: 'Snapdragon W5 Gen 1', specifications: { Chip: 'Snapdragon W5 Gen 1', Display: '1.2" AMOLED', Sensor: 'Heart rate, SpO2' }, iconImage: '/mock-images/categories/pixel-watch.png', galleryImages: ['/mock-images/categories/pixel-watch.png'], isActive: true, createdAt: '2024-02-04' },
  // Gaming > Xbox > Series X/S
  { id: 'p42', seriesId: 's20', categoryId: 'c12', brandId: 'b4', name: 'Xbox Series X', description: 'Most powerful Xbox', specifications: { CPU: 'Zen 2 8-core', GPU: '12 TFLOPS', Storage: '1TB SSD' }, iconImage: '/mock-images/categories/xbox.png', galleryImages: ['/mock-images/categories/xbox.png'], isActive: true, createdAt: '2024-02-10' },
  { id: 'p43', seriesId: 's20', categoryId: 'c12', brandId: 'b4', name: 'Xbox Series S', description: 'All-digital compact Xbox', specifications: { CPU: 'Zen 2 8-core', GPU: '4 TFLOPS', Storage: '512GB SSD' }, iconImage: '/mock-images/categories/xbox.png', galleryImages: ['/mock-images/categories/xbox.png'], isActive: true, createdAt: '2024-02-10' },
  // Gaming > PlayStation > PS5
  { id: 'p44', seriesId: 's21', categoryId: 'c13', brandId: 'b4', name: 'PlayStation 5 Standard', description: 'PS5 with disc drive', specifications: { CPU: 'Zen 2 8-core', GPU: '10.28 TFLOPS', Storage: '825GB SSD' }, iconImage: '/mock-images/categories/playstation.png', galleryImages: ['/mock-images/categories/playstation.png'], isActive: true, createdAt: '2024-02-10' },
  { id: 'p45', seriesId: 's21', categoryId: 'c13', brandId: 'b4', name: 'PlayStation 5 Digital Edition', description: 'PS5 without disc drive', specifications: { CPU: 'Zen 2 8-core', GPU: '10.28 TFLOPS', Storage: '825GB SSD' }, iconImage: '/mock-images/categories/playstation.png', galleryImages: ['/mock-images/categories/playstation.png'], isActive: true, createdAt: '2024-02-10' },
  { id: 'p46', seriesId: 's21', categoryId: 'c13', brandId: 'b4', name: 'PlayStation 5 Slim', description: 'PS5 Slim redesigned', specifications: { CPU: 'Zen 2 8-core', GPU: '10.28 TFLOPS', Storage: '1TB SSD' }, iconImage: '/mock-images/categories/playstation.png', galleryImages: ['/mock-images/categories/playstation.png'], isActive: true, createdAt: '2024-02-10' },
  // OnePlus > Number Series > 12 Series
  { id: 'p47', seriesId: 's22', categoryId: 'c14', brandId: 'b5', name: 'OnePlus 12', description: 'Snapdragon 8 Gen 3 flagship', specifications: { Chip: 'Snapdragon 8 Gen 3', Display: '6.82" LTPO AMOLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/oneplus-number.png', galleryImages: ['/mock-images/categories/oneplus-number.png'], isActive: true, createdAt: '2024-03-01' },
  { id: 'p48', seriesId: 's22', categoryId: 'c14', brandId: 'b5', name: 'OnePlus 12R', description: 'Snapdragon 8 Gen 2 value flagship', specifications: { Chip: 'Snapdragon 8 Gen 2', Display: '6.78" LTPO AMOLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/oneplus-number.png', galleryImages: ['/mock-images/categories/oneplus-number.png'], isActive: true, createdAt: '2024-03-01' },
  // OnePlus > Number Series > 11 Series
  { id: 'p49', seriesId: 's23', categoryId: 'c14', brandId: 'b5', name: 'OnePlus 11', description: 'Snapdragon 8 Gen 2', specifications: { Chip: 'Snapdragon 8 Gen 2', Display: '6.7" LTPO AMOLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/oneplus-number.png', galleryImages: ['/mock-images/categories/oneplus-number.png'], isActive: true, createdAt: '2024-03-01' },
  // OnePlus > Nord > Nord 3 Series
  { id: 'p50', seriesId: 's24', categoryId: 'c15', brandId: 'b5', name: 'OnePlus Nord 3', description: 'Dimensity 9000, mid-range', specifications: { Chip: 'Dimensity 9000', Display: '6.74" AMOLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/oneplus-nord.png', galleryImages: ['/mock-images/categories/oneplus-nord.png'], isActive: true, createdAt: '2024-03-01' },
  { id: 'p51', seriesId: 's24', categoryId: 'c15', brandId: 'b5', name: 'OnePlus Nord CE 3', description: 'Snapdragon 782G', specifications: { Chip: 'Snapdragon 782G', Display: '6.72" AMOLED', Camera: '50MP Main' }, iconImage: '/mock-images/categories/oneplus-nord.png', galleryImages: ['/mock-images/categories/oneplus-nord.png'], isActive: true, createdAt: '2024-03-01' },
];
